-- AlterTable
ALTER TABLE "Caixa" ADD COLUMN     "saldo_final" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saldo_inicial" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "saldo" SET DEFAULT 0;
